apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: disk.csi.azure.com
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_LRS  # Options: Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS
volumeBindingMode: WaitForFirstConsumer
