service:
  type: LoadBalancer
  ports:
    http: 9000
    https: 9001

# SonarQube deployment configuration
sonarqube:
  replicaCount: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "managed-csi"

# Choose your edition (one option must be set)
#edition: "developer"  # Choose "developer" or "enterprise"
# OR use Community Edition (uncomment below line)
community:
  enabled: true

# Required monitoring passcode
monitoringPasscode: "Raviteja@1995"

# Environment variables for SonarQube
env:
  - name: SONARQUBE_JDBC_URL
    value: "jdbc:postgresql://sonarqube-postgresql:5432/sonarqube"
  - name: SONARQUBE_JDBC_USERNAME
    value: "sonarqube"
  - name: SONARQUBE_JDBC_PASSWORD
    value: "sonarpassword"

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    username: "sonarqube"
    password: "sonarpassword"
    database: "sonarqube"
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "managed-csi"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
